apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example-pg-cluster
  namespace: postgresql-cluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  bootstrap:
    initdb:
      database: example_db
      owner: dbadmin
      secret:
        name: example-pg-cluster-secret
      postInitSQL:
        - CREATE DATABASE other_example_db OWNER dbadmin; # optional SQL query
  postgresql:
    parameters:
      max_connections: "1000"
  storage:
    size: 20Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_pool
                operator: In
                values:
                  - node-pool-db
  backup:
    barmanObjectStore:
      destinationPath: "s3://backup-db-example"
      s3Credentials:
        accessKeyId:
          name: example-pg-cluster-secret
          key: accessKeyID
        secretAccessKey:
          name: example-pg-cluster-secret
          key: secretAccessKey
      wal:
        compression: "gzip"
      data:
        compression: "gzip"
    retentionPolicy: "3d"
---
apiVersion: v1
kind: Service
metadata:
  name: example-pg-cluster-rw
  namespace: postgresql-cluster
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: example-pg-cluster-ro
  namespace: postgresql-cluster
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
  type: ClusterIP
