apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-pg-cluster-servicemonitor
  namespace: postgresql-cluster
spec:
  selector: {}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - postgresql-cluster
